### ISSUE TITLE
Content Migrator not detecting all children

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#58] opened 2020-10-02 07:22 UTC
I'm trying to sync in a site into a clean instance. 
From: Sitecore 9.2 with SXA, SCS 1.5.9 Rainbow 2.1.2
To: Sitecore 10.0 with SXA, SCS 1.5.9 Rainbow 2.1.2

It does not seem to be consistent with items further down the tree.
For example it brought in _/sitecore/media library/open-your-way/open-your-way-landing-page/Image Text Block/image-text-block-ColouringIn_ but not _/sitecore/media library/open-your-way/open-your-way-landing-page/Image Text Block/image-text-block-sale-and-service_ which is on the same level. I have also seen where it didn't bring in any child items after level 6. I then have to rerun the sync to bring those in, up to 5 times to bring everything in.

All advanced options are unticked.

**Comment by JeffDarchuk** [comment] 2020-10-02 13:16
Could you try clearing Sitecore caches after you run it?  I've had some people reporting this type of behavior as being caused by stale caches.

**Comment by markgibbons25** [comment] 2020-10-03 05:22
Here's an example:

![image](https://user-images.githubusercontent.com/3212534/94983747-225b4f80-0589-11eb-9abd-1fcf90ac147c.png)

So not only is the quick diff showing as no children changes detected but then doing a pull wouldn't bring that item in the first time. I'll admit that now that I have synced all content in it is harder to reproduce this problem.

Caching I don't think is relevant for this problem as this screenshot is right after a restart of both instances.

Looking through how it works, the item ID is getting retrieved by the ScsContentMigrator.Data.ChecksumGenerator but perhaps is not getting processed correctly in ScsContentMigrator.Data.Generate

By the way I have played around with changing the checksum to SHA1 just incase it was an issue with hashing collision described [here ](https://docs.microsoft.com/en-us/dotnet/api/system.string.gethashcode?view=netcore-3.1) and have also partially converted to SDK proj format so that compiling will compile against various sitecore versions at once - just to rule out a Sitecore API issue https://github.com/markgibbons25/SitecoreSidekick/tree/feature/checksum

**Comment by JeffDarchuk** [comment] 2020-10-03 05:50
The checksum generation is more complicated than that.  The checksum is generated by hashing together the revision ID with the checksum of all the children.  So the leaf node is the hash of the revision id, then the parent node is a hash of the parent revision ID combined with the checksum of the leaf node and all sibling subtrees.  This is done by querying directly to the database to make it performant.

At the point the file tree from the remote server is sent, it includes the checksum.  If the checksum is off, that means there are child changes.

I've seen some oddities in this process before, it shouldn't effect the actual sync operation as this is more of a "quick estimation" of where changes exist instead of the actual logic that drives the sync itself.

That being said, I've never gotten it to consistently screw up the checksum.  Usually it will eventually right itself, which makes it terribly frustrating to debug.  If you could provide any clues as to something on your setup that may be noteworthy it would be very helpful in debugging.

**Comment by markgibbons25** [comment] 2020-10-03 08:27
This particular checksum is definitely consistently wrong so if you have any suggestions for how to debug it? E.g. log statements? 
Also the actual sync operation as I mentioned has either the same issue or a similar one in that it doesnt bring in all children, and then when I drill down the tree in the SCS UI it shows similar to that screenshot.

**Comment by JeffDarchuk** [comment] 2020-10-04 14:22
Very interesting.  I've never seen or heard of this behavior before.  My initial thoughts are that Sidekick utilizes the revision field when determining what content should be sent over the wire.  Basically the requester sends the ID and revision ID and the sender looks up the ID and compares the revision ID, if the revision ID matches it doesn't send any payload back to avoid unneeded bytes over the wire.  I have seen a situation where Sitecore's revision ID can get messed up, that's why i added the "ignore revision id" option, could you give that a try next time?  That will skip the revision ID check i mentioned before.  It won't fix the checksum, but it should allow the sync to pull all the content if that's the problem.

**Comment by vitaliitylyk** [comment] 2020-10-05 12:15
I have noticed weird behavior related to the above as well. For example:

![image](https://user-images.githubusercontent.com/4365595/95078187-05ec1e00-0715-11eb-995f-cdf773d50326.png)

The parent item shows (red triangle) that children have differences when they actually don't according to the same UI.

**Comment by JeffDarchuk** [comment] 2020-10-05 13:13
I've noticed transient issues such as this as well.  Usually it corrects itself with a bit of time, or if all else fails after an app pool recycle.  Do you notice it consistently wrong in a particular case?

**Comment by vitaliitylyk** [comment] 2020-10-05 13:34
It is quite random. After pulling a tree of items some of them are displayed as green, some of them have red triangle but if I expand their children - all children are green. I have not noticed a consistent pattern yet.

**Comment by JeffDarchuk** [comment] 2020-10-05 13:39
I'd love to fix it, but the random nature of it makes it very hard to track down.

**Comment by alexangas** [comment] 2020-10-28 17:42
I work with @markgibbons25 on the same Sitecore instance and tried the following things today with suggestions from @JeffDarchuk.

Behaviour observed was:

* multiple runs over the same nodes are required to copy everything
* new items are only created once, i.e. problem seems to be finding or handling data structures in memory
* copying a node that does not exist at all on the destination will skip a handful of items, even though all should be copied
* no oddities in Sitecore logs and no errors reported by Content Migrator

Tried the following:

* resetting cache between a run
* running with Item Blaster (no Rainbow) and without (using Rainbow 2.1.2)
* using "bulk update context" or not
* using "ignore rev id"

**Comment by markgibbons25** [comment] 2020-10-29 06:18
I'm able to reproduce this issue on another completely different set of environments for a different client (both sitecore 10) with or without item blaster makes no difference.

**Comment by markgibbons25** [comment] 2020-10-29 06:51
From my investigation , looks like this is a bug introduced in ContentItemPuller on this commit https://github.com/JeffDarchuk/SitecoreSidekick/commit/39de49dba183614eea3bdb40d053e7d1e4a6bb9c#diff-cc1fa99df8d3d64d3ebc4ec33989a16765e8dcd33de2539ac4ad9d6803c60a8e

I think that when `if (GatheredRemoteItems.Count >= _maxQueue)` is true, it will discard those items.

**Comment by markgibbons25** [comment] 2020-10-29 08:20
I downgraded to **1.5.2** and this problem went away. 
So I would say there is a bug here that you can reproduce. All my test cases is using a remote server.

**Comment by JeffDarchuk** [comment] 2020-10-29 14:03
Ah, you're absolutely right.  Past Jeff had some serious issues with if/else logic apparently.  This is very likely what the problem is.  The speed at which item blaster processes items could explain why Alex had more success using Item blaster.  At any rate, i'll get this fixed and a new version pushed out, once i do i'll report back and close this issue.

**Comment by JeffDarchuk** [comment] 2020-10-29 17:00
1.5.10 released and should fix this.  As a side note, i was able to reproduce this locally by throttling the rate at which items are installed/created/modified into Sitecore.  I feel pretty good that it's fixed now.  Thanks again to everyone who looked into this and helped debug, it's been a very helpful exchange.

**Closed by JeffDarchuk** 2020-10-29 17:00 UTC

**Comment by markgibbons25** [comment] 2020-11-01 00:42
Hi Jeff, sorry I got this issue confused with #59 , can you reopen this one, this is about the quick diff checksum issue not the race condition issue.

**Comment by markgibbons25** [comment] 2020-11-01 01:15
Hi Jeff, sorry to bear bad news but it's not fixed.  But I got a good log about what the problem could be. I had some `ParentItemNotFoundException`  one one of the runs, so my thought is that some of the threads are processing the data in the wrong order - child items getting saved before parents.

**Comment by markgibbons25** [comment] 2020-11-01 06:03
I've tested with having `remotePullingThreads` 4 and `databaseWriterThreads ` 1, so this issue does seem to be resolved, so I've opened a new issue #63  for the case `databaseWriterThreads ` >1
